// 主窗口预加载层仅暴露经过约束的 IPC 接口。
const { contextBridge, ipcRenderer } = require('electron');

function subscribe(channel, callback) {
  const wrapped = (_event, payload) => callback(payload);
  ipcRenderer.on(channel, wrapped);
  return () => ipcRenderer.removeListener(channel, wrapped);
}

contextBridge.exposeInMainWorld('cs2Assistant', {
  getState: () => ipcRenderer.invoke('settings:get'),
  setEnabled: enabled => ipcRenderer.invoke('settings:set-enabled', enabled),
  setTheme: theme => ipcRenderer.invoke('settings:set-theme', theme),
  setAccentColor: color => ipcRenderer.invoke('settings:set-accent-color', color),
  updateBackgroundSettings: patch => ipcRenderer.invoke('settings:update-background', patch),
  chooseBackgroundImage: () => ipcRenderer.invoke('settings:choose-background-image'),
  setBombDuration: seconds => ipcRenderer.invoke('settings:set-bomb-duration', seconds),
  setOrbVisible: visible => ipcRenderer.invoke('settings:set-orb-visible', visible),
  updateOrbSettings: patch => ipcRenderer.invoke('settings:update-orb', patch),
  setMonitorOverlayVisible: visible => ipcRenderer.invoke('settings:set-monitor-overlay-visible', visible),
  updateMonitorOverlay: patch => ipcRenderer.invoke('settings:update-monitor-overlay', patch),
  setLowPerformance: enabled => ipcRenderer.invoke('settings:set-low-performance', enabled),
  setStartup: enabled => ipcRenderer.invoke('settings:set-startup', enabled),
  setAudioSettings: patch => ipcRenderer.invoke('settings:set-audio', patch),
  runSelfCheck: () => ipcRenderer.invoke('diagnostics:self-check'),
  getDiagnostics: () => ipcRenderer.invoke('diagnostics:get'),
  copyDiagnostics: () => ipcRenderer.invoke('diagnostics:copy'),
  getOnlineData: force => ipcRenderer.invoke('online-data:get', force),
  markOnlineNoticeSeen: noticeId => ipcRenderer.invoke('online-data:mark-notice-seen', noticeId),
  completeOnboarding: () => ipcRenderer.invoke('onboarding:complete'),
  restartOnboarding: () => ipcRenderer.invoke('onboarding:restart'),
  completeSetupGuide: () => ipcRenderer.invoke('setup-guide:complete'),
  resetOrbPosition: () => ipcRenderer.invoke('settings:reset-orb-position'),
  resetMonitorOverlayPosition: () => ipcRenderer.invoke('settings:reset-monitor-overlay-position'),
  chooseCfgDir: () => ipcRenderer.invoke('cfg:choose-dir'),
  autoInstallCfg: () => ipcRenderer.invoke('cfg:auto-install'),
  getCfgStatus: () => ipcRenderer.invoke('cfg:status'),
  openCfgFolder: () => ipcRenderer.invoke('cfg:open-folder'),
  testGsiPayload: () => ipcRenderer.invoke('gsi:test-payload'),
  resetGsiState: () => ipcRenderer.invoke('gsi:reset-state'),
  setCustomEnabled: enabled => ipcRenderer.invoke('custom:set-enabled', enabled),
  getCustomPresets: () => ipcRenderer.invoke('custom:get-presets'),
  addCustomPreset: presetId => ipcRenderer.invoke('custom:add-preset', presetId),
  setPresetSound: (presetId, soundPackId) => ipcRenderer.invoke('custom:set-preset-sound', presetId, soundPackId),
  savePresetSoundPack: (presetId, pack) => ipcRenderer.invoke('custom:save-sound-pack', presetId, pack),
  deletePresetSoundPack: (presetId, soundPackId) => ipcRenderer.invoke('custom:delete-sound-pack', presetId, soundPackId),
  saveEventSound: config => ipcRenderer.invoke('custom:save-event-sound', config),
  deleteEventSound: configId => ipcRenderer.invoke('custom:delete-event-sound', configId),
  testEventSound: configId => ipcRenderer.invoke('custom:test-event-sound', configId),
  testCustomSound: (ruleId, streak) => ipcRenderer.invoke('custom:test-sound', ruleId, streak),
  addCustomRule: rule => ipcRenderer.invoke('custom:add-rule', rule),
  updateCustomRule: (ruleId, rule) => ipcRenderer.invoke('custom:update-rule', ruleId, rule),
  deleteCustomRule: ruleId => ipcRenderer.invoke('custom:delete-rule', ruleId),
  testCustomRule: ruleId => ipcRenderer.invoke('custom:test-rule', ruleId),
  chooseCustomFile: kind => ipcRenderer.invoke('custom:choose-file', kind),
  chooseDemoDir: () => ipcRenderer.invoke('toolbox:choose-demo-dir'),
  scanDemos: () => ipcRenderer.invoke('toolbox:scan-demos'),
  deleteDemo: filePath => ipcRenderer.invoke('toolbox:delete-demo', filePath),
  openDemo: filePath => ipcRenderer.invoke('toolbox:open-demo', filePath),
  applyProProfile: profileId => ipcRenderer.invoke('toolbox:apply-pro-profile', profileId),
  restoreProProfile: () => ipcRenderer.invoke('toolbox:restore-pro-profile'),
  updateToolboxSettings: patch => ipcRenderer.invoke('toolbox:update-settings', patch),
  testLatency: () => ipcRenderer.invoke('toolbox:test-latency'),
  getMonitorSnapshot: () => ipcRenderer.invoke('monitor:get-snapshot'),
  quit: () => ipcRenderer.invoke('app:quit'),
  minimize: () => ipcRenderer.invoke('window:minimize'),
  close: () => ipcRenderer.invoke('window:close'),
  toggleOrb: () => ipcRenderer.invoke('window:toggle-orb'),
  onInit: callback => subscribe('app:init', callback),
  onSettings: callback => subscribe('settings:update', callback),
  onGame: callback => subscribe('game:update', callback),
  onBomb: callback => subscribe('bomb:update', callback),
  onServer: callback => subscribe('server:status', callback),
  onRuntime: callback => subscribe('runtime:update', callback),
  onCustom: callback => subscribe('custom:update', callback),
  onPlaySound: callback => subscribe('custom:play-sound', callback),
});
